# default false
release_mode = false

# default DEBUG, DEBUG INFO WARN ERROR OFF
log_level = "DEBUG"

# REDIS,FILE,COOKIE(COOKIE Default)
session_store = "REDIS"
# 32或64个英文字符
session_secret_key = "qwertyuiopasdfghjklzxcvbnmqazwsx"

# REDIS,MEMCACHED,IN_MEMORY(IN_MEMORY Default)
cache_store = "REDIS"

[app]
name = "Echo Web"

[server]
graceful = true
addr = ":8080"

# Domains
domain_api = "echo.api.localhost.com"
domain_web = "localhost"
domain_socket = "echo.socket.localhost.com"

[static]
# BINDATA,FILE(FILE Default)
type = "BINDATA"

[tmpl]
# PONGO2,TEMPLATE(TEMPLATE Default)
type = "PONGO2"
# BINDATA,FILE(FILE Default)
data = "BINDATA"
# PONGO2(template/pongo2),TEMPLATE(template)
dir = "template/pongo2"
# .html,.tpl
suffix = ".html"

[database]
name = "echo-web"
user_name = "root"
pwd  = "root"
host = "127.0.0.1"
port = "3306"

[redis]
server = "127.0.0.1:6379"
pwd = ""

[memcached]
server = "localhost:11211"

[opentracing]
disable = true

# jaeger or appdash
type = "jaeger"

# jaeger serviceName
service_name = "echo-web"

# jaeger-agent 127.0.0.1:6831
# appdash http://localhost:8700
address = "127.0.0.1:6831"